name: snaptale
description: "SnapTale — Every Picture Has a Story. No humans. Just everything else."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  web_socket_channel: ^3.0.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.4.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/snaptale_icon.png"
  adaptive_icon_background: "#FFD400"
  adaptive_icon_foreground: "assets/icon/snaptale_icon_foreground.png"